### ISSUE TITLE
T2w not defaced

### ISSUE THREAD

**Issue by julfou81** [PeerHerholz/BIDSonym#21] opened 2020-05-21 01:23 UTC
Hi, Thank you for this nice tool!

It works very well in singularity on a HPC for defacing T1w. I want to apply the mask to the T2w image and added the flag ``--deface_t2w`` to the command line but got only this error message:

``usage: bidsonym [-h]
                [--participant_label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]
                [--deid {pydeface,mri_deface,quickshear,mridefacer,deepdefacer}]
                [--deface_t2w DEFACE_T2W] [--del_nodeface {del,no_del}]
                [--check_meta CHECK_META [CHECK_META ...]]
                [--del_meta DEL_META [DEL_META ...]]
                [--brainextraction {bet,nobrainer}] [--bet_frac BET_FRAC] [-v]
                bids_dir {participant,group}
bidsonym: error: argument --deface_t2w: expected one argument``

I am not sure then what should be the command argument for T2w defacing?

Also I don't get the html report either.

Thank you for your help!

**Comment by PeerHerholz** [comment] 2020-05-22 18:48
Hi @julfou81,

thank you very much for posting this issue. 

Hm, something is indeed off here. I'll check it and provide an update asap (either during the weekend or early next week).

**Comment by julfou81** [comment] 2020-05-26 23:39
Thank you for your quick answer.  I am looking forward to seeing it fixed!

**Comment by iPsych** [comment] 2020-08-12 08:49
Hello, the issue is resolved? 
adding
**--deface_t2w** 
gives error as above.

**Comment by PeerHerholz** [comment] 2020-08-12 19:45
Hi gang,

sorry for being away so long.
I just pushed a commit that should fix this error.
As local tests worked as expected, I'm closing this issue.

**Closed by PeerHerholz** 2020-08-12 19:45 UTC
